name: Checkstyle

on:
  pull_request:

permissions:
  contents: read

jobs:
  checkstyle:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'tearing'
      - name: Run check style
        uses: avitaminosis/checkstyle-action@master
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: 'github-pr-check'
          tool_name: 'review dog'
          checkstyle_config: 'config/checkstyle/checkstyle.xml'
          workdir: 'src/main'
          level: error

    #- name: Discord Notification
    #  uses: sari/actions-status-discord@v1
    #  if: always()
    #  with:
    #    webhook: ${{ secrets.DISCORD_WEBHOOK }}
    #    status: ${{ job.status }}
    #    content: "Hey <@everyone>"
    #    title: "Checkstyle"
    #    description: "Run Checkstyle"
    #    color: "#cb88d2"
    #    url: "https://github.com/sarisia/actions-status-discord"
    #    username: GitHub Actions
