name: Checkstyle

on:
  pull_request:
    paths:
      - 'src/**/*'  # Adjust the path based on your project structure

jobs:
  checkstyle:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Run Checkstyle
        uses: avitaminosis/checkstyle-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          checkstyle_config: 'config/checkstyle/checkstyle.xml'
          workdir: 'src/main'  # Adjust the path based on your project structure
          level: error
